import { useState } from 'react';
import { ArrowUpRight, ArrowDown, Github, Linkedin, Menu, X, Download, Code2, Layers, TrendingUp } from 'lucide-react';
import { Button } from '@/components/ui/button';
import Contact from '@/components/Contact';
import portrait from '@/assets/wiz.jpeg';
import '@/portfolio.css';
const projects = [
    { title: 'Crea8', category: 'Creative agency', type: 'Websites', image: 'crea8-hero.png', description: 'An expressive digital home for a creative agency, with modern design and a considered motion system.', url: 'https://crea8-ten.vercel.app/', github: 'https://github.com/Wisdomkara/Creative' },
    { title: 'Healinton', category: 'Healthcare', type: 'Web apps', image: 'healinton-logo.png', description: 'A healthcare platform connecting patient needs with clear, accessible service workflows.', url: 'https://healinton.com/', github: 'https://github.com/Wisdomkara/Healinton' },
    { title: 'Exploits Energy', category: 'Energy & industry', type: 'Websites', image: 'exploit-logo.png', description: 'A confident corporate presence that puts the company’s energy services front and center.', url: 'https://exploitsenergy.com/' },
    { title: 'Kanel Innovations', category: 'Technology', type: 'Web apps', image: 'kanel-innovations-logo.jpg', description: 'A service and booking experience built for a technology-focused business.', url: 'https://kanelinnovations.vercel.app/' },
    { title: 'Amaechi Homes', category: 'Real estate', type: 'Websites', image: 'homes.jpg', description: 'Property discovery and enquiries brought together in a practical WordPress experience.', url: 'https://amaechihomes.com/' },
    { title: 'BokkuMart', category: 'Commerce', type: 'Web apps', image: 'bo.jpg', description: 'A React and TypeScript application with customer location tracking and Supabase integration.', url: 'https://bokku.vercel.app/', github: 'https://github.com/Wisdomkara/bokku' },
    { title: 'Insightful Tutorial Academy', category: 'Education', type: 'Websites', image: 'insightful-tech-trybe-logo.jpeg', description: 'A welcoming home for learning programs from Insightful Tech Trybe.', url: 'https://insightful-tutorial-academy.vercel.app/' }
];
export default function Index() {
    const [menuOpen, setMenuOpen] = useState(false);
    const [filter, setFilter] = useState('All work');
    return <div className="portfolio"><a className="skip-link" href="#main">Skip to content</a>
    <header className="site-header wrap"><a className="wordmark" href="#home" aria-label="Wisdom Kara home">wk<span>.</span></a><nav aria-label="Main navigation" className={menuOpen ? 'main-nav is-open' : 'main-nav'}>{['Work', 'About', 'Expertise', 'Experience'].map(label => <a key={label} href={`#${label === 'Work' ? 'projects' : label.toLowerCase()}`} onClick={() => setMenuOpen(false)}>{label}</a>)}</nav><a className="header-contact" href="#contact">Let’s talk <ArrowUpRight size={16}/></a><Button variant="ghost" size="icon" className="menu-toggle" aria-label={menuOpen ? 'Close navigation' : 'Open navigation'} aria-expanded={menuOpen} onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X /> : <Menu />}</Button></header>
    <main id="main"><section id="home" className="hero wrap"><div><div className="eyebrow"><span className="status-dot"/> FRONT-END DEVELOPER & DIGITAL PARTNER</div><h1>Thoughtful code.<br />Distinctive design.<br /><span>Real impact.</span></h1><p className="hero-intro">I’m Wisdom Kara. I build websites and digital experiences that look good, work beautifully, and help businesses move forward.</p><div className="hero-actions"><Button asChild className="primary-action"><a href="#projects">Explore my work <ArrowUpRight /></a></Button><a className="text-link" href="#contact">Have a project in mind? <ArrowUpRight size={16}/></a></div><div className="hero-note"><span>BASED IN NIGERIA</span><span className="note-line"/><span>WORKING WORLDWIDE</span></div></div><div className="portrait-composition"><div className="portrait-label">THE PERSON BEHIND THE PIXELS</div><div className="portrait-frame"><img src={portrait} alt="Wisdom Kara" fetchPriority="high"/><span className="portrait-monogram" aria-hidden="true">wk.</span></div><div className="portrait-caption"><span>Wisdom Kara<br /><small>Developer. Problem solver. Creative thinker.</small></span><ArrowDown size={22}/></div></div></section>
    <div className="tool-strip"><div className="wrap"><span className="tool-label">MY EVERYDAY TOOLKIT</span>{['React', 'TypeScript', 'Tailwind CSS', 'WordPress', 'GoHighLevel'].map(tool => <span key={tool}>{tool}</span>)}</div></div>
    <section id="projects" className="wrap section-space"><div className="section-heading"><div><div className="eyebrow">01 / SELECTED WORK</div><h2>Built with purpose.<br />Made to stand out.</h2></div><p>A selection of websites and applications<br />across industries, ideas, and ambitions.</p></div><div className="work-toolbar"><div className="filters" aria-label="Filter projects">{['All work', 'Websites', 'Web apps'].map(value => <Button key={value} variant="ghost" aria-pressed={filter === value} onClick={() => setFilter(value)} className={filter === value ? 'filter active' : 'filter'}>{value}{value === 'All work' && <span>07</span>}</Button>)}</div><span className="project-count" aria-live="polite">{projects.filter(p => filter === 'All work' || p.type === filter).length} projects</span></div><div className="project-grid">{projects.filter(p => filter === 'All work' || p.type === filter).map(project => <article className="project-card" key={project.title}><a className={`project-image ${project.image.includes('logo') ? 'logo-image' : ''}`} href={project.url} target="_blank" rel="noreferrer" aria-label={`Visit ${project.title}`}><img src={`/${project.image}`} alt={`${project.title} project preview`} loading="lazy"/><span className="project-visit"><ArrowUpRight size={23}/></span></a><div className="project-heading"><h3><a href={project.url} target="_blank" rel="noreferrer">{project.title}</a></h3><span>{project.category}</span></div><p>{project.description}</p>{project.github && <a className="source-link" href={project.github} target="_blank" rel="noreferrer"><Github size={14}/> View source <ArrowUpRight size={13}/></a>}</article>)}</div></section>
    <section id="about" className="about-section"><div className="wrap about-grid section-space"><div><div className="eyebrow">02 / A LITTLE ABOUT ME</div><h2>A developer’s mind.<br />A creative’s eye.</h2><a className="text-link" href="/wisdom-kara-cv.docx" download>Download my CV <Download size={16}/></a></div><div className="about-copy"><p>I care about the details that make a digital experience feel effortless.</p><p>With a background in Computer Science, I bring together front-end development, design thinking, and digital marketing to help businesses find their place online.</p><p>From a React application to a WordPress website, my approach stays the same: understand the people using it, make the complex feel simple, and build it with care.</p><div className="about-bottom"><span><span className="status-dot"/> Open to remote collaboration</span><a href="https://www.linkedin.com/in/wisdom-kara-" target="_blank" rel="noreferrer" aria-label="LinkedIn"><Linkedin size={20}/></a><a href="https://github.com/Wisdomkara" target="_blank" rel="noreferrer" aria-label="GitHub"><Github size={20}/></a></div></div></div></section>
    <section id="expertise" className="wrap section-space"><div className="section-heading"><div><div className="eyebrow">03 / HOW I CAN HELP</div><h2>From first idea<br />to final interaction.</h2></div><p>Design sensibility. Technical depth.<br />A focus on your business.</p></div><div className="services">{[{ icon: Code2, title: 'Front-end development', description: 'Responsive, accessible interfaces with clean code and performance in mind.', tags: 'React / TypeScript / Tailwind CSS' }, { icon: Layers, title: 'Websites & platforms', description: 'Custom websites and practical business tools that are easy to use and built to grow.', tags: 'WordPress / GoHighLevel / Web apps' }, { icon: TrendingUp, title: 'Digital growth', description: 'Connect your website to the bigger picture with search visibility and digital marketing.', tags: 'SEO / Digital marketing / Social media' }].map((s, i) => <article className="service" key={s.title}><div className="service-top"><s.icon size={28} strokeWidth={1.4}/><span>0{i + 1}</span></div><h3>{s.title}</h3><p>{s.description}</p><div className="service-tags">{s.tags}</div></article>)}</div></section>
    <section id="experience" className="wrap experience-section"><div className="eyebrow">04 / THE JOURNEY SO FAR</div><h2>Experience that<br />shapes the work.</h2><div className="experience-list">{[['2022 — Present', 'Senior Front-end Developer', 'Kanel Technologies', 'Leading responsive web application development with React and modern JavaScript.'], ['2021 — 2022', 'Front-end Developer', 'Creative Digital Solutions', 'Building user-centered interfaces and implementing modern design systems.'], ['2020 — 2021', 'Junior Web Developer', 'Tech Innovators', 'Creating websites with WordPress and custom HTML, CSS, and JavaScript.']].map(([date, title, company, description]) => <article className="experience-row" key={company}><span>{date}</span><div><h3>{title}</h3><p>{description}</p></div><span>{company}</span></article>)}</div></section><Contact /></main>
    <footer className="wrap site-footer"><a className="wordmark" href="#home">wk<span>.</span></a><span>© {new Date().getFullYear()} Wisdom Kara</span><div><a href="https://github.com/Wisdomkara" target="_blank" rel="noreferrer">GitHub <ArrowUpRight size={14}/></a><a href="https://www.linkedin.com/in/wisdom-kara-" target="_blank" rel="noreferrer">LinkedIn <ArrowUpRight size={14}/></a><a href="#home">Back to top ↑</a></div></footer></div>;
}
